version: 2
updates:
  - package-ecosystem: npm
    directory: /packages/core
    schedule:
      interval: weekly
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: vitest
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/cli
    schedule:
      interval: weekly
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: vitest
        update-types:
          - version-update:semver-major
