import { writeFileSync, mkdirSync, renameSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseFeatureFrontMatter } from "./compat/parse.js";
import { deriveSlug } from "../src/rules/compat-derive.js";
import type { DerivedCompat } from "../src/types/index.js";

// Pin to a caniemail commit SHA (set in Step 6 after the first run). Runtime never fetches.
const CANIEMAIL_REF = "770fc00";
const REPO = "hteumeuleu/caniemail";

// The §5 slug list — single source of truth for what sync fetches.
export const COMPAT_SLUGS: string[] = [
  "css-display-flex", "css-display-grid", "css-position", "css-float",
  "css-transform", "css-transition", "css-animation", "css-filter",
  "css-backdrop-filter", "css-unit-calc", "css-aspect-ratio", "css-object-fit",
  "css-mix-blend-mode", "css-function-clamp", "css-overflow", "css-border-radius",
  "css-background-image", "css-variables", "css-at-import", "css-at-font-face",
  "html-video", "html-audio", "html-link",
];

export interface CompatArtifact {
  COMPAT: Record<string, DerivedCompat>;
  COMPAT_DATA_VERSION: string;
}

// Pure: derive the artifact from a slug -> markdown map (testable offline, no network).
export function deriveFixtureCompat(input: Record<string, string>): CompatArtifact {
  const COMPAT: Record<string, DerivedCompat> = {};
  const missing: string[] = [];
  for (const slug of COMPAT_SLUGS) {
    const md = input[slug];
    if (md === undefined) { missing.push(slug); continue; }
    COMPAT[slug] = deriveSlug(parseFeatureFrontMatter(md, slug));
  }
  if (missing.length) throw new Error(`sync: missing feature files for slugs: ${missing.join(", ")}`);
  return { COMPAT, COMPAT_DATA_VERSION: "" };
}

// Deviates from spec §8.1's single-tarball fetch: uses per-slug raw GETs (23) + 1 commits API call to avoid a tar dependency. Acceptable for a manual script.
async function fetchFeature(slug: string): Promise<string> {
  const url = `https://raw.githubusercontent.com/${REPO}/${CANIEMAIL_REF}/_features/${slug}.md`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`fetch ${slug}: HTTP ${res.status}`);
  return res.text();
}

async function resolveVersion(): Promise<{ sha: string; date: string }> {
  const res = await fetch(`https://api.github.com/repos/${REPO}/commits/${CANIEMAIL_REF}`);
  if (!res.ok) throw new Error(`fetch commit: HTTP ${res.status}`);
  const j = (await res.json()) as { sha: string; commit: { committer: { date: string } } };
  return { sha: j.sha.slice(0, 7), date: j.commit.committer.date.slice(0, 10) };
}

function emit(artifact: CompatArtifact): string {
  const sorted = Object.keys(artifact.COMPAT).sort();
  const lines: string[] = [
    `// AUTO-GENERATED by scripts/sync-compat.ts from ${artifact.COMPAT_DATA_VERSION}.`,
    `// Do not edit by hand. Regenerate: npm run sync-compat`,
    `import type { DerivedCompat } from "../types/index.js";`,
    ``,
    `export const COMPAT_DATA_VERSION = ${JSON.stringify(artifact.COMPAT_DATA_VERSION)};`,
    `export const COMPAT: Record<string, DerivedCompat> = {`,
  ];
  for (const slug of sorted) {
    lines.push(`  ${JSON.stringify(slug)}: ${JSON.stringify(artifact.COMPAT[slug])},`);
  }
  lines.push("};");
  return lines.join("\n") + "\n";
}

async function main() {
  const input: Record<string, string> = {};
  for (const slug of COMPAT_SLUGS) input[slug] = await fetchFeature(slug);
  const { sha, date } = await resolveVersion();
  const artifact = deriveFixtureCompat(input);
  artifact.COMPAT_DATA_VERSION = `caniemail@${sha} (${date})`;
  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = resolve(here, "..", "src", "generated", "compat-data.ts");
  mkdirSync(dirname(outPath), { recursive: true });
  const tmpPath = outPath + ".tmp";
  writeFileSync(tmpPath, emit(artifact));
  renameSync(tmpPath, outPath); // atomic on POSIX (same dir ⇒ same filesystem)
  console.log(`sync-compat: wrote ${outPath} (${artifact.COMPAT_DATA_VERSION})`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((e) => { console.error(e); process.exit(1); });
}
